site_name: AprenMaker-Hub
site_url: https://jmuozan.github.io/AprenMaker-Hub/

repo_url: https://github.com/jmuozan/AprenMaker-Hub
repo_name: jmuozan/AprenMaker-Hub


nav:
  - Home: 
    - index.md
    - diagram-examples.md
    - content-tabs.md
    - code-examples.md
    - admonitions.md

  - About:
    - Project Info: About/about_info.md
    - License: About/license_info.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections 
    - navigation.expand     
    - navigation.top        
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Light Mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorgemunozzanon/
    - icon: fontawesome/brands/github
      link: https://github.com/jmuozan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jmunyozz?igsh=cWp2ZjQxdWQ5bTBu&utm_source=qr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jorgemunyozz
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@jmuozan
    - icon: fontawesome/solid/globe
      link: https://jmuozan.github.io/docs/
    - icon: fontawesome/solid/envelope
      link: mailto:jmuozan@gmail.com

copyright: Copyright &copy; 2025 Jorge Muñoz Zanón